### ISSUE TITLE
I tried installing StellaZone US & EU, but both of them do not work for me. Is there something I have to do?

### ISSUE THREAD

**Issue by BrandiBlitz** [Universal-Team/extras#22]
I saw this revival application called "StellaZone". I tried downloading the US & EU packages, but neither of them work.

**Comment by TheGhostboi64** [comment]
Have you tried downloading the Lite Version?

**Comment by BrandiBlitz** [comment]
> Have you tried downloading the Lite Version?

I found what I needed to do. I had to go into FBI > Titles > launch "Nintendo Zone Veiwer".

**Comment by TheGhostboi64** [comment]
> > Have you tried downloading the Lite Version?
> 
> I found what I needed to do. I had to go into FBI > Titles > launch "Nintendo Zone Veiwer".

Yknow you can download the “usapatch” thing, it’ll let you launch Nintendo zone from the homemenu without having to launch FBI.

**Comment by BrandiBlitz** [comment]
What's the USA patch? I downloaded the US version directly from Universal Updater

**Comment by BrandiBlitz** [comment]
> Yknow you can download the “usapatch” thing, it’ll let you launch Nintendo zone from the homemenu without having to launch FBI.

What's the USA patch? I downloaded the USA version directly from Universal Updater

**Comment by TheGhostboi64** [comment]
I literally just said that it lets you launch Nintendo zone from the home menu

**Comment by TheGhostboi64** [comment]
> > Yknow you can download the “usapatch” thing, it’ll let you launch Nintendo zone from the homemenu without having to launch FBI.
> 
> What's the USA patch? I downloaded the USA version directly from Universal Updater

Are you gonna close this issue or not
